DROVA_CONFIG = "DROVA_CONFIG"

DROVA_SOCKET_LISTEN = "DROVA_SOCKET_LISTEN"

WINDOWS_HOST = "WINDOWS_HOST"
WINDOWS_LOGIN = "WINDOWS_LOGIN"
WINDOWS_PASSWORD = "WINDOWS_PASSWORD"

SHADOW_DEFENDER_PASSWORD = "SHADOW_DEFENDER_PASSWORD"
SHADOW_DEFENDER_DRIVES = "SHADOW_DEFENDER_DRIVES"

DROVA_WEB_PORT = "DROVA_WEB_PORT"
DROVA_WEB_USER = "DROVA_WEB_USER"
DROVA_WEB_PASSWORD = "DROVA_WEB_PASSWORD"

# Path to a JSON file where the DrovaPoll subprocess writes its startup diagnostic results.
# Set by WorkerManager when spawning a worker so the web server can read the results.
DROVA_STATUS_FILE = "DROVA_STATUS_FILE"
