DROVA_SOCKET_LISTEN = "DROVA_SOCKET_LISTEN"

WINDOWS_HOST = "WINDOWS_HOST"
WINDOWS_HOSTS = "WINDOWS_HOSTS"
WINDOWS_LOGIN = "WINDOWS_LOGIN"
WINDOWS_PASSWORD = "WINDOWS_PASSWORD"

SHADOW_DEFENDER_PASSWORD = "SHADOW_DEFENDER_PASSWORD"
SHADOW_DEFENDER_DRIVES = "SHADOW_DEFENDER_DRIVES"

DROVA_CONFIG = "DROVA_CONFIG"
POLL_INTERVAL_IDLE = "POLL_INTERVAL_IDLE"
POLL_INTERVAL_ACTIVE = "POLL_INTERVAL_ACTIVE"
